title: 'Product Page'
data:
  tab_labels:
    -
      id: mi4dt4v8
      description_tab: Discription
      reviews_tab: Reviews
      info_tab: 'Excessive Info'
      tab_label: Description
    -
      id: mi4dwvdg
      tab_label: Reviews
    -
      id: mi4dx6zq
      tab_label: 'Excessive Info'
  category_label: Categories
  color_label: Colors
  quantity_label: 'Qty. :'
  size_label: 'Size:'
  cart_button_label: 'Add To Cart'
  buy_now_button_label: 'Buy Now'
  billing_detail_label: 'Billing details'
  product_label: PRODUCT
  subtotal_label: Subtotal
  total_label: Total
  payments:
    -
      id: micrkvfw
      payment_option: cash-on-delivery
      description: 'Pay with cash upon delivery.'
      type: new_set
      enabled: true
    -
      id: mih2fllr
      payment_option: razorpay
      key_id: rzp_test_gQKzOhDpTlvDFb
      key_secret: 4l1PGOJO4053RxLftu3cBJrf
      type: new_set
      enabled: true
    -
      id: mih2g8t2
      payment_option: stripe
      key_id: pk_test_51QsLdSKuWco7NN3KLOvOJWIDzefR4yWi1BU1dX1QkP0F9xljaEjsa0SB76Pixc3NurHx3KsijkAFln9kwkTEUyLJ00BW2HitOJ
      key_secret: sk_test_51QsLdSKuWco7NN3KNSqfLYtqT0KWaGgn2mKmUHbB77FEbssbswDIfKsFPpuAGRbI39iHzZE97H0TLIdAwP7099EJ00klOQRLuP
      type: new_set
      enabled: true
  button_text: 'Place Order'
  free_shipping_limit: 50.0
  shipping_methods:
    -
      id: mihe3r7z
      method_name: 'Charge shipping'
      shipping_charge: '23'
      type: new_set
      enabled: true
    -
      id: mihe3z3k
      method_name: 'Free shipping'
      shipping_charge: '0'
      type: new_set
      enabled: true
  empty_heading: 'Your shopping cart is empty'
  empty_description: 'Looks like you have not added anything to your cart. Go ahead & explore top categories.'
  empty_button_text: 'Continue Shopping'
  empty_button_link: /
  w_empty_heading: 'Your wishlist is empty'
  w_empty_description: 'You haven’t added any items to your wishlist yet. Browse our collections and save your favorites for later.'
  w_empty_button_text: 'Start Shopping'
  w_empty_button_link: /
