title: Package
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
          -
            handle: background_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Background Image'
          -
            handle: package_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Package Image'
          -
            handle: team
            field:
              max_items: 1
              mode: select
              collections:
                - teams
              type: entries
              display: Team
          -
            handle: services
            field:
              mode: select
              collections:
                - services
              type: entries
              display: Services
              validate:
                - required
          -
            handle: price
            field:
              type: text
              display: Price
          -
            handle: description
            field:
              type: textarea
              display: Description
          -
            handle: button_text
            field:
              default: 'Book Now'
              type: text
              display: 'Button Text'
          -
            handle: button_link
            field:
              default: /contact
              type: text
              display: 'Button Link'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
