tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: product_id
            field:
              type: text
              display: 'Product ID'
          -
            handle: name
            field:
              type: text
              display: Name
              validate:
                - required
          -
            handle: email
            field:
              type: text
              display: Email
              validate:
                - required
                - email
          -
            handle: rating
            field:
              options:
                -
                  key: 1
                  value: '1'
                -
                  key: 2
                  value: '2'
                -
                  key: 3
                  value: '3'
                -
                  key: 4
                  value: '4'
                -
                  key: 5
                  value: '5'
              type: select
              display: Rating
              validate:
                - required
          -
            handle: comment
            field:
              type: textarea
              display: Comment
              validate:
                - required
          -
            handle: parent_id
            field:
              type: text
              display: 'Parent Id'
