tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: tab_labels
            field:
              type: grid
              display: 'Tab Labels'
              instructions: 'Control labels for the three tabs'
              fields:
                -
                  handle: tab_label
                  field:
                    type: text
                    display: 'Tab Label'
                    default: Description
          -
            handle: category_label
            field:
              default: Categories
              type: text
              display: 'Category Label'
          -
            handle: color_label
            field:
              default: colors
              type: text
              display: 'Color Label'
          -
            handle: quantity_label
            field:
              default: 'Qty. :'
              type: text
              display: 'Quantity Label'
          -
            handle: size_label
            field:
              default: 'Size:'
              type: text
              display: 'Size Label'
