tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: tab_labels
            field:
              type: grid
              display: 'Tab Labels'
              instructions: 'Control labels for the three tabs'
              fields:
                -
                  handle: tab_label
                  field:
                    type: text
                    display: 'Tab Label'
                    default: Description
          -
            handle: category_label
            field:
              default: Categories
              type: text
              display: 'Category Label'
          -
            handle: color_label
            field:
              default: colors
              type: text
              display: 'Color Label'
          -
            handle: quantity_label
            field:
              default: 'Qty. :'
              type: text
              display: 'Quantity Label'
          -
            handle: size_label
            field:
              default: 'Size:'
              type: text
              display: 'Size Label'
          -
            handle: cart_button_label
            field:
              default: 'Add To Cart'
              type: text
              display: 'Cart Button Label'
          -
            handle: buy_now_button_label
            field:
              default: 'Buy Now'
              type: text
              display: 'Buy Now Button Label'
  checkout:
    display: Checkout
    sections:
      -
        display: 'New Section'
        fields:
          -
            handle: billing_detail_label
            field:
              default: 'Billing details'
              type: text
              display: 'Billing detail Label'
              listable: true
          -
            handle: product_label
            field:
              default: PRODUCT
              type: text
              display: 'Product Label'
              listable: true
          -
            handle: subtotal_label
            field:
              default: Subtotal
              type: text
              display: 'Subtotal Label'
          -
            handle: total_label
            field:
              default: Total
              type: text
              display: 'Total Label'
          -
            handle: payments
            field:
              type: replicator
              display: Payments
              collapse: true
              sets:
                payments:
                  display: Payments
                  sets:
                    new_set:
                      display: 'New Set'
                      fields:
                        -
                          handle: payment_option
                          field:
                            options:
                              -
                                key: cash-on-delivery
                                value: 'Cash on delivery'
                              -
                                key: razorpay
                                value: Razorpay
                              -
                                key: stripe
                                value: Stripe
                            type: select
                            display: 'Payment Option'
                        -
                          handle: description
                          field:
                            type: textarea
                            display: Description
                        -
                          handle: image
                          field:
                            container: assets
                            type: assets
                            display: Image
                        -
                          handle: key_id
                          field:
                            type: text
                            display: 'Key Id'
                            if:
                              payment_option: 'not cash-on-delivery'
                        -
                          handle: key_secret
                          field:
                            type: text
                            display: 'Key Secret'
                            if:
                              payment_option: 'not cash-on-delivery'
          -
            handle: button_text
            field:
              default: 'Place Order'
              type: text
              display: 'Button Text'
      -
        display: 'Shipping Methods'
        fields:
          -
            handle: free_shipping_limit
            field:
              type: float
              display: 'Free Shipping Limit'
          -
            handle: shipping_methods
            field:
              type: replicator
              display: 'Shipping Methods'
              collapse: true
              sets:
                shipping_methods:
                  display: 'Shipping Methods'
                  sets:
                    new_set:
                      display: 'New Set'
                      fields:
                        -
                          handle: method_name
                          field:
                            type: text
                            display: 'Method Name'
                        -
                          handle: shipping_charge
                          field:
                            type: text
                            display: 'Shipping Charge'
                            instructions: 'Enter shipping charge as a fixed amount of order total (e.g., 5 for $5)'
  empty_section:
    display: 'Empty Section'
    sections:
      -
        display: 'Cart Section'
        fields:
          -
            handle: empty_heading
            field:
              default: 'Your shopping cart is empty'
              type: text
              display: Heading
          -
            handle: empty_description
            field:
              type: textarea
              display: Description
          -
            handle: empty_button_text
            field:
              type: text
              display: 'Button Text'
          -
            handle: empty_button_link
            field:
              default: /
              type: text
              display: 'Button Link'
      -
        display: 'Wishlist Section'
        fields:
          -
            handle: w_empty_heading
            field:
              type: text
              display: Heading
          -
            handle: w_empty_description
            field:
              type: textarea
              display: Description
          -
            handle: w_empty_button_text
            field:
              type: text
              display: 'Button Text'
          -
            handle: w_empty_button_link
            field:
              type: text
              display: 'Button Link'
