title: 'Product Category'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Title
          -
            handle: parent
            field:
              max_items: 1
              mode: select
              taxonomies:
                - product_categories
              type: terms
              display: Parent
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
                - 'max:200'
